# Generated by Django 4.2.2 on 2023-06-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'slug')},
        ),
    ]
